/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge05;

import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testInsertMethod() {
        LinkedList testtLinkedList = new LinkedList();
        firstLinkedList.insert(5);
        assertTrue(5, firstLinkedList.insert());
    }
}
