/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

public class App {

    public static void main(String[] args) {
//        Node newNode1 = new Node("A");
//        Node newNode2 = new Node("B");
//        Node newNode3 = new Node("C");
//        Node newNode4 = new Node("D");
//        Node newNode5 = new Node("E");
//        Node newNode6 = new Node("F");
        Graph graphTest = new Graph();
        graphTest.addNode("A");
        graphTest.addNode("B");
        graphTest.addNode("C");
        graphTest.addNode("D");
        graphTest.addNode("E");
        graphTest.addNode("F");
        graphTest.addEdge((Node) graphTest.getNodes().get(1), (Node) graphTest.getNodes().get(2));
        System.out.println(graphTest.getNeighbors((Node) graphTest.getNodes().get(1)));

//        System.out.println(graphTest.getNeighbors(newNode1));
//        System.out.println(graphTest.getSize());
        System.out.println(graphTest.graphElemnts1.toString());
        System.out.println(graphTest.getSize());
    }
}
