/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package quickSort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
     @Test void quickSortTests() {
        Library classUnderTest = new Library();
        int[] testArray = {8, 4, 23, 42, 16, 15};
        int[] testArray2 = {20,18,12,8,5,-2};
        int[] testArray3 = {5,12,7,5,5,7};
        int[] testArray4 = {2,3,5,7,13,11};
        classUnderTest.quickSort(testArray,0,testArray.length-1);
        classUnderTest.quickSort(testArray2,0,testArray2.length-1);
        classUnderTest.quickSort(testArray3,0,testArray3.length-1);
        classUnderTest.quickSort(testArray4,0,testArray4.length-1);
        assertEquals("[4, 8, 15, 16, 23, 42]", Arrays.toString(testArray));
        assertEquals("[-2, 5, 8, 12, 18, 20]", Arrays.toString(testArray2));
        assertEquals("[5, 5, 5, 7, 7, 12]", Arrays.toString(testArray3));
        assertEquals("[2, 3, 5, 7, 11, 13]", Arrays.toString(testArray4));
    }
     @Test void quickSortTests1() {
        Library classUnderTest = new Library();
        int[] testArray = {};
        int[] testArray2 = {88};
        classUnderTest.quickSort(testArray,0,testArray.length-1);
        classUnderTest.quickSort(testArray2,0,testArray2.length-1);
        assertEquals("[]", Arrays.toString(testArray));
        assertEquals("[88]", Arrays.toString(testArray2));
    }
}
