/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mergeSort;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void mergeSortTests() {
        Library classUnderTest = new Library();
        int[] testArray = {8, 4, 23, 42, 16, 15};
        int[] testArray2 = {20,18,12,8,5,-2};
        int[] testArray3 = {5,12,7,5,5,7};
        int[] testArray4 = {2,3,5,7,13,11};
        assertEquals("[4, 8, 15, 16, 23, 42]", Arrays.toString(classUnderTest.mergeSort(testArray)));
        assertEquals("[-2, 5, 8, 12, 18, 20]", Arrays.toString(classUnderTest.mergeSort(testArray2)));
        assertEquals("[5, 5, 5, 7, 7, 12]", Arrays.toString(classUnderTest.mergeSort(testArray3)));
        assertEquals("[2, 3, 5, 7, 11, 13]", Arrays.toString(classUnderTest.mergeSort(testArray4)));
    }
    @Test void mergeSortTests2() {
        Library classUnderTest = new Library();
        int[] testArray = {};
        assertEquals("[]", Arrays.toString(classUnderTest.mergeSort(testArray)));
    }
    @Test void mergeSortTests3() {
        Library classUnderTest = new Library();
        int[] testArray = {8};
        assertEquals("[8]", Arrays.toString(classUnderTest.mergeSort(testArray)));
    }

}
