/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package challenge26;

import org.junit.jupiter.api.Test;

import java.util.Arrays;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void insertionSortTest() {
        InsertionSort newIns = new InsertionSort();
        int[] arr2 = {20,18,12,8,5,-2};
        int[] arr3 = {5,12,7,5,5,7};
        int[] arr4 = {2,3,5,7,13,11};
        assertEquals("[-2, 5, 8, 12, 18, 20]", Arrays.toString(newIns.insertionSort(arr2)));
        assertEquals("[5, 5, 5, 7, 7, 12]",Arrays.toString(newIns.insertionSort(arr3)));
        assertEquals("[2, 3, 5, 7, 11, 13]",Arrays.toString(newIns.insertionSort(arr4)));
    }
    @Test void insertionSortTest2() {
        InsertionSort newIns = new InsertionSort();
        int[] arr = {};
        assertEquals("[]", Arrays.toString(newIns.insertionSort(arr)));
    }

    @Test void insertionSortTest3() {
        InsertionSort newIns = new InsertionSort();
        int[] arr = {20};
        assertEquals("[20]", Arrays.toString(newIns.insertionSort(arr)));
    }
}
