/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;
import static org.junit.jupiter.api.Assertions.assertEquals;

class LibraryTest {
    @Test void instantiateEmptyTree () {
        Tree tree = new Tree();
        assertNull(tree.root);
    }
    @Test void singleRootTree () {
        Tree tree = new Tree();
        tree.root=new Node("A");
        assertNotNull(tree.root);
    }
    @Test void smallTree () {
        Tree tree = new Tree();
        tree.root=new Node("A");
        tree.root.right=new Node("B");
        tree.root.left=new Node("C");
        assertEquals("A",tree.root.value);
        assertEquals("B",tree.root.right.value);
        assertEquals("C",tree.root.left.value);
    }
    @Test void treeMethodsTests () {
        Tree tree = new Tree();
        tree.root = new Node("A");
        tree.root.right = new Node("C");
        tree.root.left = new Node("B");
        tree.root.right.left = new Node("F");
        tree.root.left.right = new Node("E");
        tree.root.left.left = new Node("D");
        assertEquals("A -> B -> D -> E -> C -> F -> ",tree.preOrder(tree.root));
        assertEquals("D -> B -> E -> A -> F -> C -> ",tree.inOrder(tree.root));
        assertEquals("D -> E -> B -> F -> C -> A -> ",tree.postOrder(tree.root));
    }
}
