/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package trees;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public static void main(String[] args) {
        kTree ktree = new kTree();
        NodeK root = new NodeK("24");
        NodeK node1 = new NodeK("15");
        NodeK node2 = new NodeK("20");
        NodeK node3 = new NodeK("65");
        NodeK node4 = new NodeK("30");
        NodeK node5 = new NodeK("555");
        NodeK node6 = new NodeK("18");

        ktree.root = root;
        root.children.add(node1);
        root.children.add(node2);
        node1.children.add(node3);
        node2.children.add(node4);
        node2.children.add(node5);
        node2.children.add(node6);
        ktree.fizzBuzz(root);

    }
}
