/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

public class Library {
    public static void main(String[] args) {
        ///// Stack

//        Stack<Integer> newStack = new Stack<>();
//        newStack.push(1);
//        newStack.push(2);
//        newStack.push(3);
//        newStack.push(4);
//        System.out.println(newStack);
//        System.out.println("value "+ newStack.pop());
//        System.out.println(newStack);
//        System.out.println("value "+ newStack.pop());
//        System.out.println(newStack);
//        System.out.println(newStack.isEmpty());
//        System.out.println(newStack.peek());

//        newStack.pop();
//        System.out.println(newStack);
//        newStack.pop();
//        System.out.println(newStack);
//        newStack.pop();
//        System.out.println(newStack);
//        newStack.pop();
//        System.out.println(newStack);

        /////// Queue

//        Queue<Integer> newQueue = new Queue<>();
//        newQueue.Enqueue(1);
//        newQueue.Enqueue(2);
//        newQueue.Enqueue(3);
//        newQueue.Enqueue(4);
//        System.out.println(newQueue);
//
//        newQueue.dequeue();
//        System.out.println(newQueue);
//
//        newQueue.dequeue();
//        System.out.println(newQueue);
//
//        newQueue.dequeue();
//        System.out.println(newQueue);
//
//        newQueue.dequeue();
//        System.out.println(newQueue);
//
//        newQueue.dequeue();

//        System.out.println(newQueue.peek());

        /////// Queue
//        PseudoQueue<Integer> newPseudoQueue = new PseudoQueue<>();
//        newPseudoQueue.pseudoEnqueue(1);
//        newPseudoQueue.pseudoEnqueue(2);
//        newPseudoQueue.pseudoEnqueue(3);
//        newPseudoQueue.pseudoDequeue();
//        System.out.println(newPseudoQueue);

        AnimalShelter<Animal> animalQueue = new AnimalShelter<>();
        Cat cat1 =new Cat("cat1");
        Cat cat2 =new Cat("cat2");
        Cat cat3 =new Cat("cat3");
        Dog dog1 =new Dog("dog1");
        Dog dog2 =new Dog("dog2");
        Dog dog3 =new Dog("dog3");
        animalQueue.animalEnqueue(cat1);
        animalQueue.animalEnqueue(cat2);
        animalQueue.animalEnqueue(cat3);
        animalQueue.animalEnqueue(dog1);
        animalQueue.animalEnqueue(dog2);
        animalQueue.animalEnqueue(dog3);

        System.out.println(animalQueue);

        animalQueue.animalDequeue("DOG");
        System.out.println(animalQueue);

        animalQueue.animalDequeue("cat");
        System.out.println(animalQueue);

        animalQueue.animalDequeue("dog");
        System.out.println(animalQueue);
    }
}
