/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stack.and.queue;

public class Library {
    public static void main(String[] args) {
        /////// Stack

//        Stack<Integer> newStack = new Stack<>();
//        newStack.push(1);
//        newStack.push(2);
//        newStack.push(3);
//        newStack.push(4);
//        System.out.println(newStack);
//        System.out.println("value "+ newStack.pop());
//        System.out.println(newStack);
//        System.out.println("value "+ newStack.pop());
//        System.out.println(newStack);
//        System.out.println(newStack.isEmpty());
//        System.out.println(newStack.peek());

//        newStack.pop();
//        System.out.println(newStack);
//        newStack.pop();
//        System.out.println(newStack);
//        newStack.pop();
//        System.out.println(newStack);
//        newStack.pop();
//        System.out.println(newStack);


        /////// Queue

        Queue<Integer> newQueue = new Queue<>();
        newQueue.Enqueue(1);
        newQueue.Enqueue(2);
        newQueue.Enqueue(3);
        newQueue.Enqueue(4);
        System.out.println(newQueue);

        newQueue.dequeue();
        System.out.println(newQueue);

        newQueue.dequeue();
        System.out.println(newQueue);

        newQueue.dequeue();
        System.out.println(newQueue);

        newQueue.dequeue();
        System.out.println(newQueue);

        newQueue.dequeue();

//        System.out.println(newQueue.peek());
    }

}
