/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hash;


public class Library {

    public static void main(String[] args) {

//        System.out.println((int) 'C');
//        System.out.println(hash();
//        System.out.println(hash("Pioneer Square"));
    }

//    public static void

//
//    public static int hash<K> ( key){
//        int sumOfAscii=0;
//        String castedKey=key.toString();
//        for(int i=0; i<castedKey.length(); i++)
//        {
//          sumOfAscii+=  (int)castedKey.charAt(i);
//            System.out.println((int)castedKey.charAt(i));
//        }
//        return  (sumOfAscii*599)%1024;
//    }
}
