/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hash;


public class Library {

    public static void main(String[] args) {
        HashTable test = new HashTable(1024);
//        System.out.println((int) 'C');
        System.out.println(test.GetHash("Ayyoub"));
//        System.out.println(test.GetHash("Mohammad"));
        test.addToHashTable("Ayyoub", "saify");
        System.out.println(test.tableArray[287].getValue());
        System.out.println("------");
        test.addToHashTable("Ayyuob", "keyyam");
        System.out.println(test.tableArray[287].next.getValue());
        System.out.println("000000000");
//        System.out.println(test.get("jj"));
        System.out.println(test.contain("Ayyoub"));
        System.out.println(test.contain("ayyoub"));


    }


//    BinaryTree tree1 = new BinaryTree();
//    tree1.root = new Node(150);
//    tree1.root.left = new Node(100);
//    tree1.root.left.left = new Node(75);
//    tree1.root.left.right = new Node(160);
//    tree1.root.left.right.left = new Node(125);
//    tree1.root.left.right.right = new Node(175);
//    tree1.root.right = new Node(250);
//    tree1.root.right.left = new Node(200);
//    tree1.root.right.right = new Node(350);
//    tree1.root.right.right.left = new Node(300);
//    tree1.root.right.right.right = new Node(500);
//
//    BinaryTree tree2 = new BinaryTree();
//    tree2.root = new Node(42);
//    tree2.root.left = new Node(100);
//    tree2.root.left.left = new Node(15);
//    tree2.root.left.right = new Node(160);
//    tree2.root.left.right.left = new Node(125);
//    tree2.root.left.right.right = new Node(175);
//    tree2.root.right = new Node(600);
//    tree2.root.right.left = new Node(200);
//    tree2.root.right.right = new Node(350);
//    tree2.root.right.right.left = new Node(4);
//    tree2.root.right.right.right = new Node(500);

}
