/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package hash;

import org.junit.jupiter.api.Test;

import java.util.NoSuchElementException;

import static org.junit.jupiter.api.Assertions.*;

class LibraryTest {
    @Test void hashTableTests() {
        HashTable hashTableTest = new HashTable(1024);
        hashTableTest.addToHashTable("Mohammad","Alsaify");
        hashTableTest.addToHashTable("Mohmmaad","Ahmad");
        assertEquals(316,hashTableTest.GetHash("Mohammad"));
        assertEquals("Alsaify",hashTableTest.tableArray[316].getValue());
        assertEquals("Alsaify",hashTableTest.get("Mohammad"));
        assertEquals("Ahmad",hashTableTest.get("Mohmmaad"));//collision
        assertEquals(true,hashTableTest.contain("Mohammad"));
        assertEquals(false,hashTableTest.contain("anas"));
        assertThrows(NoSuchElementException.class,() ->hashTableTest.get("anas"));
    }

    @Test void repeatedWordsTests() {
        RepeatedWord repeatedWordTest = new RepeatedWord();
        String test="Once upon a time, there was a brave princess who...";
        String test2 = "It was the best of times, it was the worst of times, it was the age of wisdom, it was the age of foolishness, it was the epoch of belief, it was the epoch of incredulity, it was the season of Light, it was the season of Darkness, it was the spring of hope, it was the winter of despair, we had everything before us, we had nothing before us, we were all going direct to Heaven, we were all going direct the other way – in short, the period was so far like the present period, that some of its noisiest authorities insisted on its being received, for good or for evil, in the superlative degree of comparison only...";
        String test3 = "It was a queer, sultry summer, the summer they electrocuted the Rosenbergs, and I didn’t know what I was doing in New York...";
        String test4 = "";
        assertEquals("a",repeatedWordTest.repeatedWord(test));
        assertEquals("it",repeatedWordTest.repeatedWord(test2));
        assertEquals("summer",repeatedWordTest.repeatedWord(test3));
        assertEquals("There's no repeated word",repeatedWordTest.repeatedWord(test4));

    }


}
