/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void graphTests() {
        Graph classUnderTest = new Graph();
        classUnderTest.addNode("A");
        assertEquals("[{A}]",classUnderTest.getNodes().toString());

        classUnderTest.addNode("B");
        classUnderTest.addEdge((Node) classUnderTest.getNodes().get(0), (Node) classUnderTest.getNodes().get(1));
        assertEquals("{{A}=[{B}], {B}=[]}",classUnderTest.graphElemnts1.toString());

        assertEquals("[{A}, {B}]",classUnderTest.getNodes().toString());

        assertEquals("[{B}]",classUnderTest.getNeighbors((Node) classUnderTest.getNodes().get(0)).toString());

        assertEquals(2,classUnderTest.getSize());

        assertEquals("{A}",classUnderTest.addNode("A").toString());

    }
}
