/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package graph;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test
    void graphTests() {
        Graph classUnderTest = new Graph();
        classUnderTest.addNode("A");
        assertEquals("[{A}]",classUnderTest.getNodes().toString());

        classUnderTest.addNode("B");
        classUnderTest.addEdge((Node) classUnderTest.getNodes().get(0), (Node) classUnderTest.getNodes().get(1));
        assertEquals("{{A}=[{B}], {B}=[]}",classUnderTest.graphElemnts1.toString());

        assertEquals("[{A}, {B}]",classUnderTest.getNodes().toString());

        assertEquals("[{B}]",classUnderTest.getNeighbors((Node) classUnderTest.getNodes().get(0)).toString());

        assertEquals(2,classUnderTest.getSize());

        assertEquals("{A}",classUnderTest.addNode("A").toString());

    }

    @Test
    void breadthFirst() {
        Graph graphTest = new Graph();
        graphTest.addNode("A");
        graphTest.addNode("B");
        graphTest.addNode("C");
        graphTest.addNode("D");
        graphTest.addNode("E");
        graphTest.addNode("F");

        graphTest.addEdge((Node) graphTest.getNodes().get(0), (Node) graphTest.getNodes().get(1));
        graphTest.addEdge((Node) graphTest.getNodes().get(1), (Node) graphTest.getNodes().get(2));
        graphTest.addEdge((Node) graphTest.getNodes().get(2), (Node) graphTest.getNodes().get(3));
        graphTest.addEdge((Node) graphTest.getNodes().get(2), (Node) graphTest.getNodes().get(4));
        graphTest.addEdge((Node) graphTest.getNodes().get(2), (Node) graphTest.getNodes().get(5));
        graphTest.addEdge((Node) graphTest.getNodes().get(5), (Node) graphTest.getNodes().get(0));

        assertEquals("[{E}, {C}, {A}, {B}, {D}, {F}]",graphTest.breadthFirst((Node) graphTest.getNodes().get(2)).toString());
//        assertEquals("[{D}, {B}, {A}, {C}, {E}, {F}]",graphTest.breadthFirst((Node) graphTest.getNodes().get(2)).toString());
//        assertEquals("[{A}, {D}, {F}, {C}, {B}, {E}]",graphTest.breadthFirst((Node) graphTest.getNodes().get(5)).toString());

    }

}
